### ISSUE TITLE
Add CONTRIBUTING.MD

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/HandCricket#5]
Add a Contributing guide in how to contribute to the project.
This is a **first-timers-only** Issue for people who haven't ever contributed to Open-Source

**Comment by pv2k** [comment]
I am new to the open source world, can I work on this????

**Comment by sbshah97** [comment]
Yeah sure, @pv2k Go ahead submit a Pull Request! Go through the README.md file and let me know if you have any doubts!

**Comment by pv2k** [comment]
okay:).

**Comment by sbshah97** [comment]
@pv2k kindly go through the existing `CONTRIBUTING.md` file and look for further edits. An excellent format has been shown.
