### ISSUE TITLE
Add HTML, CSS to the existing JS code

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/HandCricket#6]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by kartik95** [comment]
Has this issue been resolved? Or it still needs some changes? @salman-bhai

**Comment by sbshah97** [comment]
If you think you can make the UI better go ahead, submit a PR.

**Comment by kartik95** [comment]
Great, I'll get on to it then. :)

**Comment by sbshah97** [comment]
Good work on this! Issue closed!
